### PR TITLE
Sync to the most recent versions of Lean and mathlib4

### PR DESCRIPTION
**Pull request by yangky11**
Hi,

This PR updates the Lean version to ` v4.3.0-rc2` and fixes an error (`negIdMulLog_eq_neg`) as a result of the update.

### CODE REVIEW

**Comment by teorth** [comment]
Oops, it turns out there was a build issue with your PR:

image

I merged it a bit too prematurely, but perhaps you would be able to fix it on your end and update the PR?

**Comment by yangky11** [comment]
Looks like I forgot to run in the dev mode. Fixing it now

**Comment by yangky11** [comment]
Fixed in https://github.com/teorth/pfr/pull/27

**Comment by zeramorphic** [comment]
In the future, instead of updating `mathlib` manually, please run the `update_mathlib` script in the `scripts` directory, which I wrote to avoid this error (and a couple of other things like mismatching toolchain versions). There is a `.sh` Unix version and a `.bat` Windows version.

**Pull request merged**
