### PR TITLE
Task A.1

### PR DESCRIPTION
**Pull request by FLDutchmann**
I added the following assumptions: 
* `Fintype G`
* $X_i$ is measurable
* $\mathbb{P}_i$ is a probability measure

### CODE REVIEW

**Comment by teorth** [comment]
I think one may need to add similar assumptions to some downstream lemmas to make them compile now.

**Comment by FLDutchmann** [comment]
Yes - I am fixing those right now

**Comment by FLDutchmann** [comment]
This was a bit more involved than I had hoped. The proof of the conditional version applies this lemma on the marginal distributions. These are only probabilty distributions when $Y$ satisfies some nondegeneracy condition. I've added a sorry instead of figuring out the precise condtion on $Y$, since I don't know exactly what is true in the applications.

**Comment by teorth** [comment]
OK.  Somehow `CondMultiDist_nonneg` was overlooked in the blueprint, but I'm sure it gets used somewhere, so I will add it and also add a task to fill in the sorry.

**Pull request merged**
